name: Build Config
on:
  push:
    branches:
      - config

jobs:
  build:
    name: Test and build file config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Test
        run: npm run test

      - name: Build files
        run: npm run build

      - name: Push lib
        run: |
          git add .
          git commit -m "ci: build files config"
          git push
