name: Create Releasea by Tag
on:
  push:
    tags:
      - 'v*'

jobs:
  new_release:
    name: New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Running Composer
        run: |
          cd upload/system/library/PagSeguro
          wget -qO- https://getcomposer.org/installer | php
          php composer.phar install --no-dev
          rm composer.phar

      - name: Zip Files
        run: zip -r extension.ocmod.zip install.xml upload

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Extension Zipped
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./extension.ocmod.zip
          asset_name: extension.ocmod.zip
          asset_content_type: application/zip

  dispatch_newsletter:
    name: Dispatch Newsletter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Send emails
        uses: ./.github/actions/dispatch-newsletter
        with:
          TOKEN: ${{ secrets.AUTHENTICATION }}
          URL: ${{ secrets.URL_NEWSLETTER }}
